version: "3.3"

services:
  work-at-olist:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - apm
    environment:
      ELASTIC_APM_SERVER_URL: http://apm:8200
      ELASTIC_APM_SERVICE_NAME: work-at-olist

  elasticsearch:
    image: elasticsearch:6.5.4
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:6.5.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:6.6.0
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    volumes:
      - ./apm-server.yml:/etc/apm-server/apm-server.yml
